// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhasFinancas.Infra;

#nullable disable

namespace MinhasFinancas.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706235654_fase421_base_conhecimento_financeira")]
    partial class fase421_base_conhecimento_financeira
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.AcaoSimulacaoFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantidadeParcelas")
                        .HasColumnType("int");

                    b.Property<Guid>("SimulacaoFinanceiraId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TipoAcao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoFinanceiraId");

                    b.ToTable("AcaoSimulacaoFinanceira");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.AnaliseFinanceiraHistorica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClassificacaoSaudeFinanceira")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContextoResumoFinanceiroIAJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("CustoEstimadoUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IndicadoresResumidosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InsightsResumidosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MensagemErro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModeloIA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PerfilFinanceiroVigenteJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PerguntaUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PeriodoReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PontuacaoSaudeFinanceira")
                        .HasColumnType("int");

                    b.Property<string>("PrincipaisPontosPositivosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipaisRecomendacoesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipaisRiscosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrioridadesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProvedorIA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RespostaIA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResumoExecutivoSistema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TempoTotalMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TokensEntrada")
                        .HasColumnType("int");

                    b.Property<int>("TokensSaida")
                        .HasColumnType("int");

                    b.Property<int>("TokensTotais")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VersaoPrompt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VersaoSistema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AnaliseFinanceiraHistorica");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.AporteMeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAporte")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MetaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("AporteMeta");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.BemPatrimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeBemPatrimonial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Permanencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BemPatrimonial");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContaPadraoPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiaFechamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiaVencimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCartao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Ultimos4Digitos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cartao");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.ConfiguracaoPerfilFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicioVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MesesReservaEmergenciaDesejados")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PatrimonioLiquidoAlvo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualEconomiaMensalDesejado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualMaximoComprometimentoRenda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualMaximoEndividamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualMinimoInvestimento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualReservaEmergenciaDesejado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("PerfilFinanceiroId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilFinanceiroId");

                    b.ToTable("ConfiguracaoPerfilFinanceiro");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInvestimento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.DividaManualProjecaoMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjecaoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjecaoId");

                    b.ToTable("DividaManualProjecaoMensal");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataEfetivacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FrequenciaLancamento")
                        .HasColumnType("int");

                    b.Property<Guid?>("GrupoLancamentoProgramadoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GrupoParcelamentoId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("NumeroDiaUtil")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusLancamento")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubCategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoProgramacao")
                        .HasColumnType("int");

                    b.Property<int?>("TotalParcelas")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vinculo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("SubCategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lancamento");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.LancamentoFixo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.ToTable("LancamentoFixo");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.LancamentoParcelado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.ToTable("LancamentoParcelado");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MetaAlcancada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeMeta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PorcentagemDaMeta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorParaChegarNaMeta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Meta");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Passivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomePassivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Permanencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Passivo");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.PerfilFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PerfilFinanceiro");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.PermanenciaBemMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BemPatrimonialId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataPermanencia")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BemPatrimonialId");

                    b.ToTable("PermanenciaBemMaterial");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.PermanenciaPassivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataPermanencia")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PassivoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PassivoId");

                    b.ToTable("PermanenciaPassivo");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Projecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AtreladaADespesas")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MesesLimite")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ValorAcumuladoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Projecao");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.RendaExtraProjecaoMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjecaoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjecaoId");

                    b.ToTable("RendaExtraProjecaoMensal");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.RendaProjecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjecaoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjecaoId");

                    b.ToTable("RendaProjecao");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.SimulacaoFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeMeses")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SimulacaoFinanceira");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.SnapshotPatrimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAtivos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPassivos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SnapshotPatrimonial");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.SubCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeSubCategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.AcaoSimulacaoFinanceira", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.SimulacaoFinanceira", "SimulacaoFinanceira")
                        .WithMany("Acoes")
                        .HasForeignKey("SimulacaoFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoFinanceira");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.AnaliseFinanceiraHistorica", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.AporteMeta", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Meta", null)
                        .WithMany("AportesMeta")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.BemPatrimonial", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", null)
                        .WithMany("BensPatrimoniais")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Cartao", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Cartoes")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", null)
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.ConfiguracaoPerfilFinanceiro", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.PerfilFinanceiro", "PerfilFinanceiro")
                        .WithMany("Configuracoes")
                        .HasForeignKey("PerfilFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilFinanceiro");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Conta", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", null)
                        .WithMany("Bancos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.DividaManualProjecaoMensal", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Projecao", "Projecao")
                        .WithMany("DividasManuaisMensais")
                        .HasForeignKey("ProjecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projecao");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Lancamento", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId");

                    b.HasOne("MinhasFinancas.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MinhasFinancas.Domain.Entities.Conta", "Conta")
                        .WithMany("BensPatrimoniais")
                        .HasForeignKey("ContaId");

                    b.HasOne("MinhasFinancas.Domain.Entities.SubCategoria", "SubCategoria")
                        .WithMany()
                        .HasForeignKey("SubCategoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Cartao");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.LancamentoFixo", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Lancamento", null)
                        .WithMany("LancamentosFixo")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.LancamentoParcelado", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Lancamento", null)
                        .WithMany("LancamentoParcelado")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Meta", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", null)
                        .WithMany("Metas")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Passivo", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", null)
                        .WithMany("Passivos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.PerfilFinanceiro", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PerfisFinanceiros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.PermanenciaBemMaterial", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.BemPatrimonial", null)
                        .WithMany("DataPermanencia")
                        .HasForeignKey("BemPatrimonialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.PermanenciaPassivo", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Passivo", null)
                        .WithMany("DataPermanencia")
                        .HasForeignKey("PassivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Projecao", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Projecoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.RendaExtraProjecaoMensal", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Projecao", "Projecao")
                        .WithMany("RendasExtrasMensais")
                        .HasForeignKey("ProjecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projecao");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.RendaProjecao", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Projecao", "Projecao")
                        .WithMany("Rendas")
                        .HasForeignKey("ProjecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projecao");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.SimulacaoFinanceira", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("SimulacoesFinanceiras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.SnapshotPatrimonial", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Usuario", null)
                        .WithMany("SnapshotsPatrimoniais")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.SubCategoria", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Categoria", null)
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.BemPatrimonial", b =>
                {
                    b.Navigation("DataPermanencia");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Conta", b =>
                {
                    b.Navigation("BensPatrimoniais");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Lancamento", b =>
                {
                    b.Navigation("LancamentoParcelado");

                    b.Navigation("LancamentosFixo");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Meta", b =>
                {
                    b.Navigation("AportesMeta");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Passivo", b =>
                {
                    b.Navigation("DataPermanencia");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.PerfilFinanceiro", b =>
                {
                    b.Navigation("Configuracoes");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Projecao", b =>
                {
                    b.Navigation("DividasManuaisMensais");

                    b.Navigation("Rendas");

                    b.Navigation("RendasExtrasMensais");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.SimulacaoFinanceira", b =>
                {
                    b.Navigation("Acoes");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Bancos");

                    b.Navigation("BensPatrimoniais");

                    b.Navigation("Cartoes");

                    b.Navigation("Categorias");

                    b.Navigation("Lancamentos");

                    b.Navigation("Metas");

                    b.Navigation("Passivos");

                    b.Navigation("PerfisFinanceiros");

                    b.Navigation("Projecoes");

                    b.Navigation("SimulacoesFinanceiras");

                    b.Navigation("SnapshotsPatrimoniais");
                });
#pragma warning restore 612, 618
        }
    }
}
