<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MinhasFinancas.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Scalar" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Scalar.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinhasFinancas.Application\MinhasFinancas.Application.csproj" />
    <ProjectReference Include="..\MinhasFinancas.CrossCutting\MinhasFinancas.CrossCutting.csproj" />
    <ProjectReference Include="..\MinhasFinancas.Infra\MinhasFinancas.Infra.csproj" />
  </ItemGroup>

</Project>
